// IMAP message → hermes context row.
//
// Pure: parsed message in, row out. No network, no clock, no I/O, so every
// branch is assertable without an IMAP server.
//
// The entity id follows the registry in ops/INGESTION.md:
//   mail:<Message-ID>   normalized — trimmed, enclosing <> stripped, host
//                       lowercased
//   fallback            mail:<account>:<folder>:<uidvalidity>:<uid>
//
// The fallback is not decoration. Message-ID is *supposed* to be globally
// unique and permanent, but it is generated by the sending client and plenty
// of them omit it — drafts, some automated senders, a few mailing-list
// rewriters. Keying on UID alone would have been simpler and wrong: UIDs are
// per-folder and reset whenever UIDVALIDITY changes, so the same message
// moved between folders would ingest twice under two ids.

// 16 KiB, matching the ceiling in ops/CONNECTORS.md. Long threads quote
// themselves without limit; the digest wants the message, not the thread's
// accumulated history, and an unbounded body is how one newsletter becomes a
// meaningful fraction of the corpus.
export const DEFAULT_MAX_BODY_BYTES = 16 * 1024;

// Only the local part is case-sensitive per RFC 5322; the domain is not. So a
// Message-ID differing only in host case is the SAME message, and lowercasing
// exactly the host is what makes the id stable across servers that rewrite it.
export function normalizeMessageId(raw) {
  if (typeof raw !== 'string') return null;
  const trimmed = raw.trim().replace(/^<+/u, '').replace(/>+$/u, '').trim();
  if (!trimmed) return null;
  const at = trimmed.lastIndexOf('@');
  if (at === -1) return trimmed;
  return trimmed.slice(0, at) + '@' + trimmed.slice(at + 1).toLowerCase();
}

export function mailEntityId({ messageId, account, folder, uidValidity, uid }) {
  const normalized = normalizeMessageId(messageId);
  if (normalized) return `mail:${normalized}`;
  if (!account || !folder || uidValidity === undefined || uid === undefined) return null;
  return `mail:${account}:${folder}:${uidValidity}:${uid}`;
}

// Addresses are sorted so an identical recipient set always renders the same
// string. Without it, a server reordering To: on a re-fetch would look like an
// edit and churn an update through hermes for a message that never changed.
export function normalizeAddresses(value) {
  const list = Array.isArray(value?.value) ? value.value : Array.isArray(value) ? value : [];
  const addresses = list
    .map((a) => (typeof a === 'string' ? a : a?.address))
    .filter((a) => typeof a === 'string' && a.length > 0)
    .map((a) => a.trim().toLowerCase());
  return [...new Set(addresses)].sort();
}

// Truncation is on BYTES, not characters: the cap exists to bound what lands
// in SQLite, and a naive slice() on a multi-byte body both overshoots the
// budget and can split a character in half.
export function clampBody(text, maxBytes = DEFAULT_MAX_BODY_BYTES) {
  const s = typeof text === 'string' ? text : '';
  const buf = Buffer.from(s, 'utf8');
  if (buf.length <= maxBytes) return { text: s, truncated: false };
  // Decode the prefix and drop a trailing replacement char if the cut landed
  // mid-sequence.
  let out = buf.subarray(0, maxBytes).toString('utf8');
  if (out.endsWith('�')) out = out.slice(0, -1);
  return { text: out, truncated: true };
}

// Quoted history and signature blocks are the bulk of a long reply and none of
// it is new information — the quoted part is already ingested as its own
// message. Cutting at the first quote marker keeps the row about what this
// sender actually wrote.
export function stripQuotedReply(text) {
  if (typeof text !== 'string') return '';
  const lines = text.split(/\r?\n/u);
  const cut = lines.findIndex(
    (line) =>
      /^\s*On .+ wrote:\s*$/u.test(line) ||
      /^\s*-{2,}\s*Original Message\s*-{2,}\s*$/iu.test(line) ||
      /^\s*_{10,}\s*$/u.test(line) ||
      /^--\s*$/u.test(line)
  );
  return (cut === -1 ? lines : lines.slice(0, cut)).join('\n').trimEnd();
}

export function messageToRow(
  parsed,
  { account, folder, uid, uidValidity, maxBodyBytes = DEFAULT_MAX_BODY_BYTES } = {}
) {
  const entityId = mailEntityId({
    messageId: parsed?.messageId,
    account,
    folder,
    uidValidity,
    uid,
  });
  // No id at all means nothing can dedupe it, and an un-dedupable row would
  // re-insert on every scan. Dropping is the honest outcome.
  if (entityId === null) return null;

  const date = parsed?.date instanceof Date ? parsed.date.getTime() : Date.parse(parsed?.date);
  // A message with no usable Date lands at "now" in a naive implementation,
  // which silently backdates the whole corpus toward the scan time. Drop it.
  if (!Number.isFinite(date)) return null;

  const from = normalizeAddresses(parsed?.from);
  const to = normalizeAddresses(parsed?.to);
  const cc = normalizeAddresses(parsed?.cc);
  const subject = typeof parsed?.subject === 'string' ? parsed.subject.trim() : '';

  const bodySource =
    typeof parsed?.text === 'string' && parsed.text.length > 0
      ? parsed.text
      : typeof parsed?.textAsHtml === 'string'
        ? parsed.textAsHtml.replace(/<[^>]*>/gu, ' ')
        : '';
  const { text: body, truncated } = clampBody(
    stripQuotedReply(bodySource).replace(/\n{3,}/gu, '\n\n').trim(),
    maxBodyBytes
  );

  const header = subject ? `"${subject}"` : '(no subject)';
  return {
    ts: date,
    source: 'mail',
    entity_id: entityId,
    // Mail attributes an author by address, not by voice. This is the
    // sanctioned side of the no-voiceprints line, same as granola's.
    speaker: from[0] ?? null,
    text: body ? `${header}\n\n${body}` : header,
    meta: {
      subject,
      from,
      to,
      cc,
      folder,
      uid,
      uidvalidity: uidValidity,
      ...(truncated ? { truncated: true } : {}),
    },
  };
}
